<?php
/**
 * Functions which enhance the theme by hooking into WordPress
 *
 * @package MFYAH_2024
 */

/**
 * For pages with view sections, fetches list of Youtube videos
 * $item_key is the array number starting from 0
 * returns Youtube video object
 */
function mfyah_2024_fetch_youtube_videos($item_key) {
 
	// $youtube_api_key = MFYAH2024_YOUTUBE_API_KEY;
	// $playlist_id = "PLJ9RDCFrPeRg3k5wQtY4n0P6Swrmanf7p";
	
	$youtube_api_key = get_option( 'mfyah2024_youtube_api_key' );
	$playlist_id = get_option( 'mfyah2024_youtube_playlist' );
	$max_items = 1;

	$youtube_fetch_url = "https://www.googleapis.com/youtube/v3/playlistItems?playlistId=" . $playlist_id . "&part=snippet&key=" . $youtube_api_key . "&maxResults=" . $max_items;

	// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
	$ch = curl_init();
 
	// curl_setopt($ch, CURLOPT_URL, $youtube_fetch_url);
	// curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

	curl_setopt_array($ch, array(
    CURLOPT_URL => $youtube_fetch_url,
    CURLOPT_RETURNTRANSFER => true,
    CURLOPT_ENCODING => "",
    CURLOPT_MAXREDIRS => 5,
    CURLOPT_TIMEOUT => 30,
    CURLOPT_CUSTOMREQUEST => "GET",
    CURLOPT_HTTPHEADER => array(
        "Content-Type: application/json",
				"Cache-Control: no-cache, no-store, must-revalidate",
				"Pragma: no-cache",
				"Expires: 0"
    ) ,
	));

	$response = curl_exec($ch);
	if (curl_errno($ch)) {
			echo 'Error:' . curl_error($ch);
	}
	curl_close($ch);

	// convert response to valid JSON format
	$res = json_decode($response, true);

	$item_details = [
		'thumbnail' => $res['items'][$item_key]['snippet']['thumbnails']['maxres']['url'],
		'id' => $res['items'][$item_key]['snippet']['resourceId']['videoId'],
		'title' => $res['items'][$item_key]['snippet']['title'],
		'description' => $res['items'][$item_key]['snippet']['description'],
	];

	return $item_details;

}
add_filter( 'mfyah_2024_get_latest_video', 'mfyah_2024_fetch_youtube_videos', $item_key ?? 0 );